# -*- coding: utf-8 -*-
texts = [u'- Vi tar en taxi.',
         u'- Där springer en hare. Den är inte så snabb, den skulle man kunna fånga.',
         u'- Ja, jag tycker den är fin, jag.',
         u'- Fast man vill ju gärna ha lite mjölk till kaffet.',
         u'- Om vi laddar upp bilderna i eftermiddag så borde jag hinna med allt.',
         u'- Nu måste vi få dit benet, kanske vända uppochned på bordet.',
         u'- Nä, mamma, man kan inte glömma sin egen födelsedag.',
         u'- Kyrkan ligger väl bakom tågstationen.',
         u'- Jag åker kanske innan de andra.',
         u'- De sa att barn inte är välkomna på bröllopet.',
         u'- När det gäller jobb, då det väl bara att fortsätta leta.',
         u'- Det ska alltså vara en sol, en måne och en stjärna.',
         u'- Den här ingången får man inte använda.',
         u'- Men hon låter ju alltid ironisk när hon pratar.',
         u'- Nja, jag tror inte jag skulle passa så bra som hovmästare.',
         u'- Jaha, men chefen håller alltid David om ryggen.',
         u'- Mintgröna byxor skulle vara snyggt till.',
         u'- Hörlurar som är helt täta vore bäst.',
         u'- Kanske det, men jag tycker nog att sista delen av debatten var lite ensidig.',
         u'- I år, då är både Ryssland och Vitryssland med.',
         u'- Den där katten, den gula katten, den är grannens.',
         u'- Jo, men Andersson är hemma imorgon.',
         u'- Jo, jag är ganska bra på att inkludera folk.',
         u'- Den behöver vatten, socker och växtnäring.']
